version: '3.3'
services:
  wp:
    image: wordpress:latest
    depends_on:
      - mdb_theproblemshop
    environment:
      - VIRTUAL_HOST=theproblemshop.com
      - VIRTUAL_PORT=80
      - WORDPRESS_DB_HOST=mdb_theproblemshop:3306
      - WORDPRESS_DB_PASSWORD=password
      - LETSENCRYPT_HOST=theproblemshop.com
      - LETSENCRYPT_EMAIL=scdgalindo@gmail.com 
    expose:
      - 80
    restart: unless-stopped
    volumes:
      - wp_data_theproblemshop:/var/www/html
  mdb_theproblemshop:
    image: mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
    volumes:
      - db_data_theproblemshop:/var/lib/mysql
volumes:
  db_data_theproblemshop:
  wp_data_theproblemshop:

networks:
  default:
    external:
      name: nginx-proxy
